# 넘파이_ndarray(array(), .shape, ndarray.ndim) 

In [2]:
import numpy as np

array() - 리스트와 같은 다양한 인자 입력받아 ndarray로 변환

shape변수 - ndarray의 차원과 크기(행/열)을 튜플 형태로 나타냄

In [6]:
array1 = np.array([1,2,3])
print('array1 type : ', type(array1))
print('array1 array 형태 :', array1.shape)

array2 = np.array([[1,2,3],[2,3,4]])
print('array2 type : ', type(array2))
print('array2 array 형태 :', array2.shape)

array1 type :  <class 'numpy.ndarray'>
array1 array 형태 : (3,)
array2 type :  <class 'numpy.ndarray'>
array2 array 형태 : (2, 3)


ndarray.ndim - 차원

In [22]:
print('array1 : {:0}차원'. format(array1.ndim))
print('array2 : {:0}차원'. format(array2.ndim))
print('array1 : {:0}차원, array2 : {:10}차원'. format(array1.ndim, array2.ndim))

array1 : 1차원
array2 : 2차원
array1 : 1차원, array2 :          2차원


# ndarray 데이터타입(.dtype, .astype())

dtype - ndarray 내의 데이터타입

만일 다른 데이터 유형이 섞여있는 리스트를 ndarray로 변경하면 데이터 크기가 더 큰 데이터 타입으로 형변환을 일괄적용

In [23]:
list1 = [1,2,3]
print(type(list1))

<class 'list'>


In [24]:
array1 = np.array(list1)
print(type(array1))

<class 'numpy.ndarray'>


In [25]:
print(array1, array1.dtype)

[1 2 3] int32


In [32]:
list2 = [1,2,'test']       # string
array2 = np.array(list2)
print(type(array2))
print(array2, array2.dtype)

list3 = [1,2,3.0]          # float
array3 = np.array(list3)
print(array3, array3.dtype)

<class 'numpy.ndarray'>
['1' '2' 'test'] <U11
[1. 2. 3.] float64


In [34]:
array_int = np.array([1,2,3])
array_float = array_int.astype('float64')  # astype 데이터프레임타입 바꾸기
print(array_float, array_float.dtype)

array_int1 = array_float.astype('int32')
print(array_int1, array_int1.dtype)

[1. 2. 3.] float64
[1 2 3] int32


# ndarray 편리하게 생성 - arange, zeros, ones

In [5]:
sequence_array = np.arange(10)
print(sequence_array)
print(sequence_array.dtype, sequence_array.shape)  # dtype 가장 큰 데이터

[0 1 2 3 4 5 6 7 8 9]
int32 (10,)


In [6]:
zero_array = np.zeros((3,2), dtype = 'int32')
print(zero_array)
print(zero_array.dtype, zero_array.shape)

[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2)


In [8]:
one_array = np.ones((3,2))
print(one_array)
print(one_array.dtype, one_array.shape)  # float

[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64 (3, 2)


# reshape_ndarray 차원&크기 변경 

In [9]:
array1 = np.arange(10)
print('array1:\n', array1)

array1:
 [0 1 2 3 4 5 6 7 8 9]


In [15]:
array2 = array1.reshape(2,5)  # 사이즈 벗어나면 error
print('array2:\n', array2)

array2:
 [[0 1 2 3 4]
 [5 6 7 8 9]]


In [16]:
array3 = array1.reshape(5,2)
print('array3:\n', array3)

array3:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


-1 인자 적용 -> 원래 ndarray와 호환되는!! 새 shape 변환(사이즈 불가능하면 error)

In [23]:
array1 = np.arange(10)
array2 = array1.reshape(-1,5)
print(array2)
print('array2 shape:', array2.shape)

array3 = array1.reshape(5,-1)
print(array3)

[[0 1 2 3 4]
 [5 6 7 8 9]]
array2 shape: (2, 5)
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


.reshape(-1,1) 형태 자주 사용됨

In [34]:
array1 = np.arange(8)
array3d = array1.reshape(2,2,2)
#print(array3d)
print('array3d:\n', array3d.tolist())

print(type(array3d.tolist()))
# tolist method는 array를 python의 list로 바꿔줌. array의 차원을 그대로 유지

array3d:
 [[[0, 1], [2, 3]], [[4, 5], [6, 7]]]
<class 'list'>


In [45]:
array5 = array3d.reshape(-1,1)  #3d -> '2d'
print('array5 : \n', array5)
print('array5 : \n', array5.tolist())
print(array5.shape)

array5 : 
 [[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]]
array5 : 
 [[0], [1], [2], [3], [4], [5], [6], [7]]
(8, 1)


In [44]:
array6 = array1.reshape(-1,1)  # 1d -> 2d
print('array6 : \n', array6)
print('array6 : \n', array6.tolist())

array6 : 
 [[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]]
array6 : 
 [[0], [1], [2], [3], [4], [5], [6], [7]]
